### ISSUE TITLE
graph title format

### ISSUE THREAD

**Issue by wz237** [worldbank/ietoolkit#73]
I was trying to create a graph with a long title but the title cannot be shown in full length. So I wrote the code below:

iegraph 	treat, ///
		title	("how easy or difficult is it to find out how the LGA is spending its budget" ///
		, size(small) position(11)) 

But the title doesn't change at all. I'm wondering how can I adjust the size and style of the title?

Thanks,
Wenqing

**Comment by kbjarkefur** [comment]
@mrimal , I think I know the issue for this, and if I am correct this should be easy. 

We are allowing users to use any **two-way graph** option. The issue @wz237 describes come from the fact that **iegraph** has a *title()* option, and there is a *title()* option in **two-way graph** that work slightly differently. 

**iegraphs**'s *title()* option takes a string and that string is the title to be used and nothing else. We are passing the string used in *title()* as a string inside quotes in row 296 and 300 like this: ``title("`title'")``.

**two-way graph**'s *title()* option can take multiple arguments where one of them is the title string. The other options are text size etc.

If someone is using the **two-way graph**'s *title()* option with more arguments than just the title text, it is incorrectly detected as **iegraphs**'s *title()* that does not allow those arguments.

The solution to this issue is to call **iegraphs**'s *title()* something else. Like *basicititle* or something else, and then have an if-statement that uses the correct one of them. Or set them in a order that the one over-rules the other or something.

**Comment by mrimal** [comment]
Fixed on commit 5baeffc . Will be merged with the main folder in the next update.

**Comment by kbjarkefur** [comment]
will close when update is published on SSC

**Comment by wz237** [comment]
Hi,
I have the ietoolkit updated to the latest version but the title still cannot function as same as it functions in two-way graph. For example, after running the code below, the title cannot appear in two lines.

```
	#delimit ;
		reg 		new_train_offnber treat;
		iegraph 	treat,  
					title	("How many LGA officials participated in training" "in the last 12 months?") 
					ytitle	("mean",height(6)) 
					xlabel	(,angle(45)) 
					ylabel  (0(10)190, axis(1) angle(horizontal) labsize(*.8) grid) 
					yline	(15 186,lp(solid))
					legend	(label(1 "Control") label(2 "ULGSP")) 
					save	("$output/new_train_offnber.png") grey;
		#delimit cr;	
```

**Comment by kbjarkefur** [comment]
This is fixed but not yet published. We will publish together with other pending bug-fixes
